package crystalspider.harvestwithease.handler;

import java.util.NoSuchElementException;

import org.slf4j.Logger;

import com.mojang.logging.LogUtils;

import crystalspider.harvestwithease.ModLoader;
import crystalspider.harvestwithease.api.HarvestWithEaseAPI;
import crystalspider.harvestwithease.config.ModConfig;
import net.minecraft.core.BlockPos;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.world.level.LevelAccessor;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.state.BlockState;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.Mod.EventBusSubscriber;
import net.neoforged.fml.common.Mod.EventBusSubscriber.Bus;
import net.neoforged.neoforge.event.level.BlockEvent.BreakEvent;

/**
 * {@link BreakEvent} event handler.
 * Handles the {@link BreakEvent} event to break-harvest and drop xp when possible.
 * See {@link #handle(BreakEvent)} for more details.
 */
@EventBusSubscriber(modid = ModLoader.MOD_ID, bus = Bus.FORGE)
public final class BreakEventHandler {
  /**
   * Logger.
   */
  private static final Logger LOGGER = LogUtils.getLogger();

  /**
   * Listens and handles the {@link BreakEvent} event.
   * If configured to do so, drops xp when breaking a mature crop.
   * 
   * @param event
   */
  @SubscribeEvent
  private static void handle(BreakEvent event) {
    try {
      LevelAccessor world = event.getLevel();
      BlockState blockState = event.getState();
      Block block = blockState.getBlock();
      if (!world.isClientSide() && ModConfig.getGrantedExp() > 0 && HarvestWithEaseAPI.isCrop(block) && HarvestWithEaseAPI.isMature(blockState)) {
        block.popExperience((ServerLevel) world, event.getPos(), ModConfig.getGrantedExp());
      }
    } catch (NullPointerException | NoSuchElementException | ClassCastException e) {
      BlockPos pos = event.getPos();
      LOGGER.debug("Exception generated by block at [" + pos.toShortString() + "]");
      LOGGER.debug("This is a non blocking error, but can result in incorrect behavior for mod " + ModLoader.MOD_ID);
      LOGGER.debug("Most probably the cause of this issue was that a non-crop ID was added in the configuration and its age property could not be retrieved, see stack trace for more details", e);
    }
  }
}
