buildscript {
  configurations.configureEach {
    resolutionStrategy {
      force 'commons-io:commons-io:2.16.1'
      force 'org.apache.commons:commons-compress:1.26.2'
    }
  }
}

plugins {
  id "org.sonarqube" version "7.2.3.7755"
  id "com.hypherionmc.modutils.modpublisher" version "2.2.1" apply false
  // https://projects.neoforged.net/neoforged/moddevgradle
  id "net.neoforged.moddev" version "2.0.141" apply false
  // https://fabricmc.net/develop/
  id "net.fabricmc.fabric-loom" version "1.16-SNAPSHOT" apply false
}

sonar {
  properties {
    property "sonar.projectKey", "Crystal-Nest_$mod_id_kebab"
    property "sonar.organization", "crystal-nest"
    property "sonar.projectVersion", mod_version
    property "sonar.host.url", "https://sonarcloud.io"
    property "sonar.qualitygate.wait", "true"
  }
}

tasks.register("publishAll") {
  group = "publishing"
  description = "Publish all loader specific versions to all platforms"
  dependsOn subprojects.publishLoader
}
