# Every field must be added to the root build.gradle expandProps map.

# Common
mod_version = 9.0.0.3-beta
group = it.crystalnest
mod_authors = Crystal Spider, Moonstone Webber, Noir
mod_title = Harvest with ease
mod_id = harvest_with_ease
mod_id_kebab = harvest-with-ease
license = GPL-3.0-or-later
description = Don't break crops, right click them!
credits =
github_user = crystal-nest
curseforge_id = 602171
minecraft_version = 1.19.2
minecraft_version_range = [1.19.2,)

# Fabric
fabric_version = 0.77.0+1.19.2
fabric_loader_version = 0.14.14

# Forge
forge_version = 43.2.0
forge_loader_version_range = [43,)

# Dependencies
cobweb_version = 1.0.0
fcap_version = 4.2.11

# Gradle
org.gradle.jvmargs = -Xmx4G
org.gradle.daemon = false
