# Every field must be added to the root build.gradle expandProps map.

# Common
mod_version = 9.1.0
group = it.crystalnest
mod_authors = Crystal Spider, Moonstone Webber, Noir
mod_title = Harvest with ease
mod_id = harvest_with_ease
mod_id_kebab = harvest-with-ease
license = GPL-3.0-or-later
description = Don't break crops, right click them!
credits =
github_user = crystal-nest
curseforge_id = 602171
minecraft_version = 1.19.4
minecraft_version_range = [1.19.4,)

# Fabric
fabric_version = 0.87.2+1.19.4
fabric_loader_version = 0.14.21

# Forge
forge_version = 45.2.0
forge_loader_version_range = [45,)

# Dependencies
cobweb_version = 1.0.0
fcap_version = 6.0.2

# Gradle
org.gradle.jvmargs = -Xmx4G
org.gradle.daemon = false
