# Every field must be added to the root build.gradle expandProps map.

# Common
java_version = 21
mod_version = 9.2.0
group = it.crystalnest
mod_authors = Crystal Spider, Moonstone Webber, Noir
mod_title = Harvest with ease
mod_id = harvest_with_ease
mod_id_kebab = harvest-with-ease
license = GPL-3.0-or-later
description = Don't break crops, right click them!
credits =
github_user = crystal-nest
curseforge_id = 602171
minecraft_version = 1.21
# https://parchmentmc.org/docs/getting-started#choose-a-version
parchment_version = 2024.06.23
# https://projects.neoforged.net/neoforged/neoform
neo_form_version = 1.21-20240613.152323

# Fabric
fabric_version = 0.100.6+1.21
fabric_loader_version = 0.15.11

# NeoForge
neoforge_version = 21.0.59-beta
neoforge_loader_version_range = [21.0,)

# Dependencies
cobweb_version = 1.1.2
fcap_version = 21.0.1

# Gradle
org.gradle.jvmargs = -Xmx4G
org.gradle.daemon = false
